name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup ZMK
        uses: zmkfirmware/zmk/.github/actions/setup-zmk@v0.3

      - name: Build firmware
        run: west build -b nice_nano_v2
